#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 07 19:32:24 ART 2025
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Insanity-Shader-Universal-v1.650.zip
enableShaders=false
